# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='Quotes',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='Users',
        ),
        migrations.AddField(
            model_name='quote',
            name='liked_by_id',
            field=models.ManyToManyField(related_name='likes', to='user_dashboard.User'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
